### ISSUE TITLE
The map problem is back! 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#143]
![screenshot - 18_05_2015 16_45_12](https://cloud.githubusercontent.com/assets/8819910/7683134/56efd6f4-fd7d-11e4-93e1-f7e1118d0a76.png)

**Comment by runjak** [comment]
Thanks for the screenshot. I think I'll try to change my current approach to this problem. Up until now I've tried to catch all events that imply a possible size change for the map, and to than fix the maps size.
It appears that this approach still doesn't catch all necessary cases. To fix this I'd like to introduce a piece of code that runs repeatedly by a timed interval, and checks if the map is of correct size. Also this issue is related to #164, and I'll close both at once.

**Comment by PaulHeggarty** [comment]
I have not seen this behaviour for a while now, and #164 has been applied, so for now I think this can be closed.
