### ISSUE TITLE
Add a separate favicon ('options' cog?) for the /admin section (also on IELex2)

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#294]

**Comment by runjak** [comment]
Since we already had a favicon for the main site and I wanted to get a different icon without spending to much time on icon creation, I've reused the existing icon and colored it read for the admin area.
![reddish](https://cloud.githubusercontent.com/assets/5417642/13218578/e5dc337a-d96a-11e5-9f78-aa0cbbed3ed1.png)
