### ISSUE TITLE
Website access

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#296]
It looks like one cannot open the website when connection to the server is still running on the same computer. This probably caused my access problem a few days ago.

**Comment by runjak** [comment]
Yes - when you're accessing the internal network via VPN configuration can be a bit tricky.
I'm currently running a custom configuration on my machine to fix this problem,
but I think it's a network problem for the institute rather than a problem with our setup.
If you want to talk to the it department about this it may be helpful for them to see the route changes I usually do to get access to the server:
```
lingdb="134.76.24.144"
tun=$(ip addr show dev tun0|grep inet|sed -e 's/ \+inet //'|sed -e 's/\/.\+//')
sudo ip route add $lingdb via $tun
```
They should than be able to push the necessary route via their VPN.

**Comment by runjak** [comment]
Since I don't really see how I can improve this situation I'll close the issue.
