### ISSUE TITLE
Any upload of csv or sql files must trigger clear cache on server AND all users 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#300]
This is becoming a nightmare.  Most changes I am making are just not showing on the website at all.  Every time, to be sure, I have to clear the server cache, clear my own browser cache, and force reload. I've had to do that a dozen times just this morning.  It's unworkable like this.
If it's not possible to clear the user's cache remotely, then can you send signals to override the cache?  For the first reload of any view after any upload of csv or sql.
Also, on completion of any upload, please show the message:  "server cache cleared".

**Comment by runjak** [comment]
I think I have some ideas about preventing the browser to cache data we don't want it to cache.
The serverside cache should already be cleared each time an import happens, but I will verify that and add the requested message.

-----

Note to myself:
I will merge the `php` branch back into `master` since most of the current development is happening there. The general issue of transitioning to python on the serverside will have to be tackled separately.

**Comment by runjak** [comment]
From my tests the situation is as such:
* Cache clearing is already working server side.
  I've added the requested message to the import feature and will deploy this soon.
* In the browser the database parts aren't cached, but instead are reloaded each time you see the loading bar.
  This is the normal site loading behavior.
  Template files for site layout are cached at the moment - a thing I'll potentially adjust in the future.
