### ISSUE TITLE
Tab title does not change when switching study or user language

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#310]

**Comment by runjak** [comment]
I have problems reproducing this in either Firefox or Chromium.
I'll try again on the online version to compare it against my local setup.

**Comment by runjak** [comment]
It appears that there is an issue with at least some of the translations for studies not being handled correctly.
Compare below screenshot to see that some studies have a `translation` but not a `title translation`.
![issue](https://cloud.githubusercontent.com/assets/5417642/13395359/982dc4e8-deee-11e5-9402-02f7cdbd80b4.png)

**Comment by runjak** [comment]
As a first step to fix this I've changed the site to use the translation of the study name rather than the study name as a fallback in case that there is no study title translation found.
But I still need to fix the input for study titles because it appears that there isn't an input for every study:
![names](https://cloud.githubusercontent.com/assets/5417642/13395538/b71227b8-deef-11e5-8666-6339d5490728.png)
![titles](https://cloud.githubusercontent.com/assets/5417642/13395539/b7137a32-deef-11e5-8a29-8091372967af.png)
