### ISSUE TITLE
Word search/filter box should reset to zero when changing view

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#357]
Todo extracted from description:
- [x] Clear search/filter on view change
- [x] Use search/filter in next/prev functionality.

-----

Currently changing view gives a blank entry in both search/filter boxes in the word selector column, but continues to limit the words shown to the last filter applied there (in either the spelling or phonetic filter box).  Probably best is to keep the search applying when switching view, but also *keep the characters entered* in the search/filter box.  
Fixing this is top priority.

**Comment by PaulHeggarty** [comment]
Less of a priority, so level 1, is that the search/filter box does not affect the next/previous choices, when arguably it should.  I.e., if the search is set to words that end in n, then the next/previous list should be same as the list in the current search, so if that returns only three words, then next/previous cycles through those three words only.

**Comment by runjak** [comment]
I've implemented both aspects and will close this issue once the changes are deployed.

**Comment by runjak** [comment]
There is an interesting glitch now possible:
* View a word like `eight`
* Filter for `^o` to yield only `one, oven`
* Observe that both, next and prev, are `oven`

This is a general problem because the current word can be different from the current filterset. So that figuring out the relative position of the current word to the list of filtered words would add additional complexity which I'll ignore for now.
