### ISSUE TITLE
Sound File Quality Control

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#373]
The quality of the recordings for these languages (or the indicated words in them) seems dubious.  Please check and compare to the original recording to see whether anything went wrong in the process of converting between sound file formats.
- [x]  Many words, including some of the low numbers, include a nasty click noise at the start in:  http://www.soundcomparisons.com/#/en/Romance/language/Brazil%3A%20Natal

For other sound files, please remove extraneous background noises.
- [x]  'woman' in http://www.soundcomparisons.com/#/en/Malakula/language/Burmbar%3A%20Fartavo

**Comment by LauraWae** [comment]
I have cleaned up the edges of Brazil: Natal within the following words:
two, three, four, wool, my, -ly. I have re-uploaded the files to the server and they are working on the website.

I have cleaned up the edge of 'woman' in Burmbar: Fartavo.

**Comment by LauraWae** [comment]
These are Giovanni's comments from 17th of July:

- Rce_It_NinS_Basil_Picerno_Dl

- [ ] to_see: the second too_see (which actually means I_see) has not been included

- Rce_It_NinS_Basil_Tito_Dl

- [ ] let_us_hope: the first consonant [ʃ] has been cut

- Rce_It_NinS_Sicily_SanFratello_Dl

- [ ] 
leaf: the first consonant [f] has been cut (now it sounds as [p])

- Rce_It_NinS_Sicily_NovaraSicilia_Dl

- [ ] let_us_hope: the first consonant [s] has been cut
- [ ] the third your_sg must be changed in your_pl_fem

- Romanian - Maramures - MM Ieud

- [ ] the second dead_fem is actually a different pronunciation of ‘said’

- Rce_It_Isl_Cors_CisM_Bastia_Town_Dl

- [ ] twenty: the first consonant has been cut 
- [ ] worm: the first consonant has been cut

- Rce_It_Nth_Vto_Lag_VeniceCity_Dl

- [ ] all_fem: the part after ‘tutta’ (from [s] onward) should be cut off

- Rce_It_Nth_LomW_Bri_Barlassina_Dl

- [ ] mother: please, cut the first consonant before [m]
- [ ] straight: please, cut the first syllable due to hesitation
- [ ] tooth: in the old folder I had also a pronunciation [diːntʃ]
- [ ] finger: this lexical item is now missing, but in the old folder I had [d̪˳iːt̪ʰ]
- [ ] goat: in the audio file there is also another pronunciation which was not labeled in Praat: [ˈkxɑːpɾɐ]

- Rce_It_Nth_LomE_Bre_Lumezzane_Dl

- [ ] taste: this word is actually “to_taste”
- [ ] let_us_hope: please, check whether an initial [h] has been cut off


- Rce_Ib_NCtm_Gal_Ctl_MindE_Foz_Dl

- [ ] egg_File_2: this is the same of the other file for ‘egg’
- [ ] he_says_subj: this is actually ‘said’
- [ ] said: this is actually ‘he_says_subj’

- Rce_Ib_NCtm_Gal_East_AstTr_Tapia_Dl

- [ ] young: this is actually ‘new’
- [ ] he_says_subj: this is actually ‘said’
- [ ] said: this is actually ‘he_says_subj’
- [ ] serve_ipv_pl: audio file corrupted
- [ ] carry_you_pl: audio file corrupted

- Rce_Ib_NCtm_Ast_Ctl_Std

- [ ] year_2: this is the same audio file of ‘year’

- Rce_Ib_NCtm_Ast_Ctl_Std

- [ ] he_says_subj: this is actually ‘said’
- [ ] said: this is actually ‘he_says_subj’
- [ ] carry_you_pl: audio file corrupted

- Rce_Fr_Sth_Alp_Vald_ValGermanascaPrali_Dl

- [ ] wind: this is actually a variant of ‘gold’, and so the word for ‘wind’ is not marked up
