### ISSUE TITLE
'Select all in this set' does not work

### ISSUE THREAD

**Issue by GAbete** [lingdb/Sound-Comparisons#376]
When you are in the LgsxWds or WdsxLgs page, in the 'meaning sets' area, the command 'select all in this set' does not work.

**Comment by runjak** [comment]
Ok - so my understanding is that we're talking about the `+` button in this screenshot:
![screenshot_2016-06-20_12-29-28](https://cloud.githubusercontent.com/assets/5417642/16191057/aebc8374-36e2-11e6-962b-db09817c9bb0.png)
From my tries in chromium and firefox clicking this button does work.
A problem is: when the set of words isn't filtered down much it takes a long time for the site to react. This is due to the large number of transcriptions that need to be processed and displayed by the browser.
I've made a screenshot of all meanings in some languages:
![screenshot_2016-06-20_12-32-34](https://cloud.githubusercontent.com/assets/5417642/16191162/31f11610-36e3-11e6-8670-eeca112f51dc.png)
Even if I zoom out to the maximum possible in chromium the scrollbar on the right still indicates that the table is about twice my screen high.

There is no obvious fix to this speed issue:
* Our current idea is to let users choose what they want to display and so if they choose all words we can only let them wait.
* The alternative would be to somehow limit what users can display but this is hard to do without limiting the usability of the site.

**Comment by GAbete** [comment]
No, I'm referring to a different button. You must first go in the LgsxWds page (or in the WdsxLgs); below "meaning sets" there is a button that allows to "select all in this set". This is the one that does not work.

**Comment by runjak** [comment]
Ah, thanks for clarifying - this appears to be broken indeed.

**Comment by runjak** [comment]
I've developed a fix for this and will close this issue when I'm deploying it to the server.
