### ISSUE TITLE
Problems in languages in database on map (colouring)

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#383]
One language in Romania and one in Portugal appear in white on this map, which they shouldn't.  Try to work out why and fix this.

![screenshot - 2016-06-22 00_47_22](https://cloud.githubusercontent.com/assets/8819910/16248957/f53b8026-3812-11e6-9fdd-a0e08ae2d8c7.png)

**Comment by runjak** [comment]
Current screenshot from [soundcomparisons.com](http://soundcomparisons.com/#/en/Romance/map/eight/Lgs_All):
![screenshot_2016-06-23_13-23-53](https://cloud.githubusercontent.com/assets/5417642/16301461/d089ca6a-3945-11e6-977c-f4da452e1c3e.png)
I assume this was a database problem that has already been fixed by someone :+1:.
