### ISSUE TITLE
Offline Version bugs

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#406]
- [x] The offline version does not seem to work on browsers other than Chrome.
- [x] On Chrome, it also asks to load the data files each time one tries to open a new study/family.  Is there an easy way of avoiding this?
- [x] The site defaults to a huge zoom out to the earth as seen from the moon, or something, so it would be nice if it defaulted to the normal map zoom setting.

**Comment by runjak** [comment]
I've just had a look at this and was able to fix the offline version for firefox easily.

Also when switching studies the site does not ask for the data files again. When a new tab is opened however, it has to do this currently, and avoiding this would cost more work than is useful.

Lastly the default zoom is fixed in the offline version.

All these changes will, of course, only take effect with the next export.
