### ISSUE TITLE
SQL transcription uploads fail to overwrite previous entries in database

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#430]
Using the admin website, I just uploaded new SQL files for 8 transcriptions that I reviewed for consistency and accuracy. However, the old transcriptions are still showing up. This can be seen in any of the following varieties of Mapudungun:

- Mpg_Arg_Cbt_LagoRosario
- Mpg_Arg_Nqn_JuninDeLosAndes_NahuelMapi
- Mpg_Arg_RNg_Jacobacci
- Mpg_Chl_Rgn9_Angol_Chacaico
- Mpg_Chl_Rgn9_CholChol_Malalche
- Mpg_Chl_Rgn9_Curarrehue_Trancura
- Mpg_Chl_Rgn9_Dollinco_Rucapangue
- Mpg_Chl_Rgn9_Freire_Huilio

Among other things, the versions currently up on the site _do not_ have syllable breaks annotated (e.g. [ wɐ̝ˈɻɐ̝ŋkɐ̝̥ ]), while the versions I just uploaded but which are not displaying _do_ have them (e.g. [ wɐ̝.ˈɻɐ̝ŋ.kɐ̝̥ ]). That should make it very easy for anyone to see if the uploads are being processed successfully or not.

At first glance, this bug may appear to be related to #422, but I don't think it is, because I _was_ able to upload a new transcription (Mpg_Chl_Rgn14_SanJoseMariquina_Maiquillahue), and it's working fine.

**Comment by Bibiko** [comment]
This should be related to the issue of clearing the browser's cache and the site cache (logged in as admin) since I can see the latest modifications.
<img width="432" alt="s" src="https://cloud.githubusercontent.com/assets/16273/22626485/a76b35da-ebae-11e6-9fa8-8f29144c9c48.png">

**Comment by Linguista** [comment]
The variety you posted a screenshot of is a new one that I uploaded for the first time last night, and it does indeed display correctly for both of us.

The problems are occurring with the 8 varieties that I mentioned above. They already had transcriptions, but last night I uploaded new and improved ones which are not displaying. I've used seven different browsers, all with their caches cleared, and the new versions of the transcriptions are still not displayed. I even used the Tor Browser Bundle to see if there is some caching server between me and the site that is causing this, but the problem persists:

![image](https://cloud.githubusercontent.com/assets/5791472/22630333/78b4f858-ebf8-11e6-9ec0-fd336ef32210.png)

It seems that when new SQL files are uploaded for varieties that already have transcriptions, the script that processes them cannot overwrite old entries. 

Whatever the cause, a hacky and temporary (but effective and very easy) solution would be to implement #429, which needs to be done anyway.

**Comment by Bibiko** [comment]
I found the reason. The used SQL statement` ... ON DUPLICATE KEY UPDATE ...` is wrong – or better on the new database (mariadb) this syntax doesn't work anymore. I will inform you about the new syntax soon.

@PaulHeggarty  This also means that the Praat script `extractWAVFile` has to be changed as well. I'll do it after fixing this issue.

**Comment by Linguista** [comment]
Note to self... This will require modifying the Praat script I use to extract transcriptions and audio from recordings, too.

**Comment by Linguista** [comment]
@Bibiko Do let me know what the new MariaDB command should be, please.

**Comment by Bibiko** [comment]
The files on ownloud `extractWAVFiles.praat` and `extractWAVFiles_Ariel.praat` were updated with the correct SQL INSERT statement.

Since the problem only occurred while updating existing records, it is **not** necessary to re-run this script for those languages which were created for the first time. 

For the records:
The first part until `ON DUPLICATE KEY UPDATE` is **unchanged**.
Here is the correct syntax after `ON DUPLICATE KEY UPDATE ...`

`ON DUPLICATE KEY UPDATE Phonetic=VALUES(Phonetic), SpellingAltv1=VALUES(SpellingAltv1), SpellingAltv2=VALUES(SpellingAltv2), NotCognateWithMainWordInThisFamily=VALUES(NotCognateWithMainWordInThisFamily), CommonRootMorphemeStructDifferent=VALUES(CommonRootMorphemeStructDifferent), DifferentMeaningToUsualForCognate=VALUES(DifferentMeaningToUsualForCognate), ActualMeaningInThisLanguage=VALUES(ActualMeaningInThisLanguage), OtherLexemeInLanguageForMeaning=VALUES(OtherLexemeInLanguageForMeaning), RootIsLoanWordFromKnownDonor=VALUES(RootIsLoanWordFromKnownDonor), RootSharedInAnotherFamily=VALUES(RootSharedInAnotherFamily), IsoCodeKnownDonor=VALUES(IsoCodeKnownDonor), DifferentMorphemeStructureNote=VALUES(DifferentMorphemeStructureNote), OddPhonology=VALUES(OddPhonology), OddPhonologyNote=VALUES(OddPhonologyNote), UsageNote=VALUES(UsageNote), SoundProblem=VALUES(SoundProblem);`

**Comment by Linguista** [comment]
Bibiko, could you send me one of the SQL files that your script creates so that I can make sure mine is producing the same output?

**Comment by Linguista** [comment]
I've modified the relevant Praat script (ownCloud: `SndComp/All - Scripts for Praat/Scott/MaSCoT-for-SOtAL--EXPERIMENTAL.praat`) to produce SQL files that are compatible with the new database system, using @Bibiko's code snippet. The problem is now resolved as far as I can see, so I'm closing the issue.
