### ISSUE TITLE
Enhancing auto-create-tiers-and-speech-segments.praat

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#434]
I have some questions that I need answered in order to enhance the `auto-create-tiers-and-speech-segments.praat` script.

1. I need a couple sample filenames of Brazil and Malakula recordings so that I can program the autodetect logic.

2. Could you confirm that `Brazil_index.txt` and `Malakula_index.txt`, as seen on ownCloud, are the two files that need to be read to extract the information that is inserted into the text grids?

3. @PaulHeggarty, you had mentioned that you could produce new files with just the things I need to have the script insert into text grids, but that's really not necessary. Assuming that the two `*_index.txt` files mentioned above are the ones that contain the required info, just let me know what columns should be inserted into what tiers (by name rather than number, please).

4. @PaulHeggarty, you had mentioned adding a new tier. Kindly let me know what it should be called, what info it should contain, and where I should grab that info from.

**Comment by PaulHeggarty** [comment]
On (1)
* All Brazil filenames start with:  `Br_`
e.g. Br_Tup_Monde_CintaLarga_Roosevelt_Dl
e.g. Br_Arw_Sth_BoliviaPanara_TKCh_Terena_Miranda_Dl  

All Oceanic (including Malakula) filenames start with:  `Oce_`
(Oceanic, because this database will go wider than Malakula, and indeed wider than Vanuatu, eventually)
e.g. Oce_Van_Mal_East_Sth_Uliveo_Lurtes_Dl
e.g. Oce_Van_Mal_East_Sth_Uliveo_Pelongk_Dl

**Comment by PaulHeggarty** [comment]
Just look for `Oce_`.  It can be made more sophisticated later, if need be.

**Comment by PaulHeggarty** [comment]
On (2), I can confirm that the files seem to be the right ones, as far as I know!

**Comment by PaulHeggarty** [comment]
On (3), safer that @LauraWae should say, to ensure consistency with how she has been doing it so far.  The hassle has been the switch to labelling in Portuguese rather than English for the Brazil project.  
I’m pretty sure only one tier needs data entering, because the rest are filled in (using the index file as a correspondence table) by the later script to segment the master recording into the individual word by word sound files.

**Comment by PaulHeggarty** [comment]
On (4), I can’t remember!  @LauraWae, can you remember?

**Comment by LauraWae** [comment]
Hi both,

I confirm Paul's answers to (1) and (2) .

On (3):

> Assuming that the two *_index.txt files mentioned above are the ones that contain the required info, just let me know what columns should be inserted into what tiers (by name rather than number, please).

The first column ("gloss") needs to be filled into the tier called "Rfc Form" (tier number 1). The second column, "Protoform" goes to tier 2, called "Protoform" (not that much of a surprise, I suppose). The third and fourth columns ("ixelicitation" and "ixmorph") go to tier 3, called "Index". Not that much of a surprise all that, I suppose ;).

On (4):

I don't remember about a 14th tier neither, sorry!

**Comment by Linguista** [comment]
Thanks for the answers, guys. @LauraWae, I have one final question: if `ixelicitation` and `ixmorph` go into the same tier, should anything separate them (e.g. `_`)?

**Comment by Linguista** [comment]
One _additional_ question. There are three sets of `*_index.txt` files. I assume the ones in the `OLD format index files` folder should not be used, but it's not clear to me if I should work with the ones in the `NEW format index files` folder of those that are in the top level of the `All - Scripts for Praat` folder.

**Comment by LauraWae** [comment]
Hi,

> 
@LauraWae, I have one final question: If ixelicitation and ixmorph go into the same tier, should anything separate them (e.g. _)?

That's a good question. I do not exactly know what those numbers are, apart form identifying the gloss. Also, when the "extractWAVFiles" produces the name, the ixmorph number is not considered i.g. does not appear on the long file name (e.g. Quechua files). 

Maybe @Bibiko knows more? 

> One additional question. There are three sets of *_index.txt files. I assume the ones in the OLD format index files folder should not be used, but it's not clear to me if I should work with the ones in the NEW format index files folder, or those that are in the top level of the All - Scripts for Praat folder.

Please use those that are in the top level. Thanks.

**Comment by PaulHeggarty** [comment]
On (3), it is a *bad* idea to fill in any other tiers than the single one that is necessary, which is `Rfc Form` (tier number 1), I presume.  This is because this is just a first automated run, to be corrected manually as necessary.  If any correction needs to be made, it should be very simple, just one tier, not correcting all four tiers.  That is a recipe for inconsistencies.  The later stage script fills in all the others anyway, correctly, automatically, on the basis of the index file.  So please write the script for this stage to insert values *only* in ``Rfc Form` .

**Comment by PaulHeggarty** [comment]
As for which folder to use the index files from, Laura is right, but for me personally, this really offends my brain and eyes, to have files of radically different forms and purposes, produced and run by different people, all lumped together.  It may be 'the new logic', but it's a mess.  
Instead there should be a dedicated subfolder for index files, and index files only.  
The reason this hasn't been done is because it entails adjusting *all* the praat scripts that use the index files, including Hans-Jörg's.  But Scott, if you are happy to tweak them so that they all look for index files in their own separate sub-folder, I would much prefer that, and start sending my programmatic updates of those files to said subfolder.

**Comment by Linguista** [comment]
> As for which folder to use the index files from, Laura is right, but for me personally, this really offends my brain and eyes, to have files of radically different forms and purposes, produced and run by different people, all lumped together. It may be 'the new logic', but it's a mess.

Agreed.

> Instead there should be a dedicated subfolder for index files, and index files only.
The reason this hasn't been done is because it entails adjusting all the praat scripts that use the index files, including Hans-Jörg's. But Scott, if you are happy to tweak them so that they all look for index files in their own separate sub-folder, I would much prefer that, and start sending my programmatic updates of those files to said subfolder.

I've looked over the Malakula and Brazil index files, and it's notable that there are none in the `OLD format Index files` folder. It's likewise of note that the versions in the top-level Praat script folder and the `NEW format index files` folder seem to be identical for these two language groups.

So with regard to these two languages, the top-level (`All - Scripts for Praat`) index files could simply be deleted to prevent confusion.

With respect to the Mapudungun index files, all three have **Quechua** proto-forms, so I'm wondering if they're used for anything at all, as these forms don't show up on the website as far as I can tell.

As to all the other index files, is any language being worked on by two or more people, using two different workflows, scripts and therefore index files? If not, then all the latest index files, whatever their format, could be placed in the same folder.

**Comment by LauraWae** [comment]
Hi,
There maybe Giovanni from Italy and Ariel from Brasília using the Romance or the Brazil index. However, we could simply notify them of the changing of folders. If nobody has any objections to it, I will create one folder where all index files go, called "All Index Files".

**Comment by PaulHeggarty** [comment]
I’ve already done some re-structuring on OwnCloud.  I don’t like the idea of the name `All Index Files`, because `All` is used elsewhere for things that apply to all users, all sections of Sound Comparisons.  
In any case, I’ve also moved the 'OLD' and 'NEW' format files into the old backups folder now, since that's all they’re needed for by now, for reference.  
The one remaining question is whether the new `Index Files` folder should be within the praat scripts folder, or in the root folder (where I’ve put it for now).

**Comment by Linguista** [comment]
> The one remaining question is whether the new Index Files folder should be within the praat scripts folder, or in the root folder (where I’ve put it for now).

If they're only used by/for Praat scripts, I'd recommend putting them in the Praat script folder.

**Comment by Linguista** [comment]
@PaulHeggarty, once you're done with these comments, either close the issue or let me know so I can do so. I've made a new issue for the new and improved Praat script.

**Comment by PaulHeggarty** [comment]
It's within the praat scripts folder for now, so let's leave it there.  The index files are also used by Hans-Jörg for some other purposes perhaps, but I think this will do for now.
